<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修异常处理' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>异常处理</center></div><div class='banquan'>原文出处:本文由博客园博主changxin7提供。<br/>
原文连接:https://www.cnblogs.com/changxin7/p/11329933.html</div><br>
    <h2 id="一异常和错误"><strong>一，异常和错误</strong></h2>
<h4 id="part1程序中难免出现错误而错误分成两种">part1:程序中难免出现错误，而错误分成两种</h4>
<p>1.语法错误（这种错误，根本过不了python解释器的语法检测，必须在程序执行前就改正）</p>
<pre><code><code>#语法错误示范一
if

#语法错误示范二
def test:
    pass

#语法错误示范三
print(haha

语法错误</code></pre>
<p>语法错误</p>
<p>2.逻辑错误（逻辑错误）</p>
<pre><code><code>#用户输入不完整(比如输入为空)或者输入非法(输入不是数字)
num=input(&quot;&gt;&gt;: &quot;)
int(num)

#无法完成计算
res1=1/0
res2=1+&#39;str&#39;</code></pre>
<p>逻辑错误</p>
<h4 id="part2什么是异常">part2:什么是异常</h4>
<p>异常就是程序运行时发生错误的信号，在python中,错误触发的异常如下</p>
<p><img src="./images/异常处理0.png" alt="img" /></p>
<h4 id="part3python中的异常种类">part3：python中的异常种类</h4>
<p>在python中不同的异常可以用不同的类型（python中统一了类与类型，类型即类）去标识，不同的类对象标识不同的异常，一个异常标识一种错误</p>
<pre><code><code># 触发IndexError
l=[&#39;egon&#39;,&#39;aa&#39;]
l[3]
# 触发KeyError
dic={&#39;name&#39;:&#39;egon&#39;}
dic[&#39;age&#39;]

#触发ValueError
s=&#39;hello&#39;
int(s)</code></pre>
<p>错误举例</p>
<pre><code><code>AttributeError 试图访问一个对象没有的树形，比如foo.x，但是foo没有属性x
IOError 输入/输出异常；基本上是无法打开文件
ImportError 无法引入模块或包；基本上是路径问题或名称错误
IndentationError 语法错误（的子类） ；代码没有正确对齐
IndexError 下标索引超出序列边界，比如当x只有三个元素，却试图访问x[5]
KeyError 试图访问字典里不存在的键
KeyboardInterrupt Ctrl+C被按下
NameError 使用一个还未被赋予对象的变量
SyntaxError Python代码非法，代码不能编译(个人认为这是语法错误，写错了）
TypeError 传入对象类型与要求的不符合
UnboundLocalError 试图访问一个还未被设置的局部变量，基本上是由于另有一个同名的全局变量，
导致你以为正在访问它
ValueError 传入一个调用者不期望的值，即使值的类型是正确的</code></pre>
<p>常用异常</p>
<pre><code><code>ArithmeticError
AssertionError
AttributeError
BaseException
BufferError
BytesWarning
DeprecationWarning
EnvironmentError
EOFError
Exception
FloatingPointError
FutureWarning
GeneratorExit
ImportError
ImportWarning
IndentationError
IndexError
IOError
KeyboardInterrupt
KeyError
LookupError
MemoryError
NameError
NotImplementedError
OSError
OverflowError
PendingDeprecationWarning
ReferenceError
RuntimeError
RuntimeWarning
StandardError
StopIteration
SyntaxError
SyntaxWarning
SystemError
SystemExit
TabError
TypeError
UnboundLocalError
UnicodeDecodeError
UnicodeEncodeError
UnicodeError
UnicodeTranslateError
UnicodeWarning
UserWarning
ValueError
Warning
ZeroDivisionError</code></pre>
<p>更多异常</p>
<h2 id="二异常处理"><strong>二，异常处理</strong></h2>
<h3 id="什么是异常"><strong>什么是异常？</strong></h3>
<p>异常发生之后</p>
<p>异常之后的代码就不执行了</p>
<h3 id="什么是异常处理">什么是异常处理</h3>
<p>python解释器检测到错误，触发异常（也允许程序员自己触发异常）</p>
<p>程序员编写特定的代码，专门用来捕捉这个异常（这段代码与程序逻辑无关，与异常处理有关）</p>
<p>如果捕捉成功则进入另外一个处理分支，执行你为其定制的逻辑，使程序不会崩溃，这就是异常处理</p>
<h3 id="为什么要进行异常处理"><strong>为什么要进行异常处理？</strong></h3>
<p>python解析器去执行程序，检测到了一个错误时，触发异常，异常触发后且没被处理的情况下，程序就在当前异常处终止，后面的代码不会运行，谁会去用一个运行着突然就崩溃的软件。</p>
<p>所以你必须提供一种异常处理机制来增强你程序的健壮性与容错性</p>
<h3 id="如何进行异常处理">如何进行异常处理？</h3>
<p><strong>首先须知，异常是由程序的错误引起的，语法上的错误跟异常处理无关，必须在程序运行前就修正</strong></p>
<h3 id="一-使用if判断式">**一： 使用if判断式</h3>
<pre><code><code>num1=input(&#39;&gt;&gt;: &#39;) #输入一个字符串试试
int(num1)</code></pre>
<p>正常代码</p>
<pre><code><code>num1=input(&#39;&gt;&gt;: &#39;) #输入一个字符串试试
if num1.isdigit():
    int(num1) #我们的正统程序放到了这里,其余的都属于异常处理范畴
elif num1.isspace():
    print(&#39;输入的是空格,就执行我这里的逻辑&#39;)
elif len(num1) == 0:
    print(&#39;输入的是空,就执行我这里的逻辑&#39;)
else:
    print(&#39;其他情情况,执行我这里的逻辑&#39;)

&#39;&#39;&#39;
问题一：
使用if的方式我们只为第一段代码加上了异常处理，但这些if，跟你的代码逻辑并无关系，这样你的代码会因为可读性差而不容易被看懂

问题二：
这只是我们代码中的一个小逻辑，如果类似的逻辑多，那么每一次都需要判断这些内容，就会倒置我们的代码特别冗长。
&#39;&#39;&#39;</code></pre>
<p>使用if判断进行异常处理</p>
<p>总结：</p>
<p>1.if判断式的异常处理只能针对某一段代码，对于不同的代码段的相同类型的错误你需要写重复的if来进行处理。</p>
<p>2.在你的程序中频繁的写与程序本身无关，与异常处理有关的if，会使得你的代码可读性极其的差</p>
<p>3.if是可以解决异常的，只是存在1,2的问题，所以，千万不要妄下定论if不能用来异常处理。</p>
<pre><code><code>def test():
    print(&#39;test running&#39;)
choice_dic={
    &#39;1&#39;:test
}
while True:
    choice=input(&#39;&gt;&gt;: &#39;).strip()
    if not choice or choice not in choice_dic:continue #这便是一种异常处理机制啊
    choice_dic[choice]()</code></pre>
<p>你之前用的异常处理机制</p>
<h3 id="二python异常处理的私人定制"><strong>二：python异常处理的'私人定制'</strong></h3>
<p><strong>python：为每一种异常定制了一个类型，然后提供了一种特定的语法结构用来进行异常处理</strong></p>
<h4 id="part1基本语法"><strong>part1:基本语法</strong></h4>
<pre><code><code>try:
     被检测的代码块
except 异常类型：
     try中一旦检测到异常，就执行这个位置的逻辑</code></pre>
<pre><code><code>f = open(&#39;a.txt&#39;)

g = (line.strip() for line in f)
for line in g:
    print(line)
else:
    f.close()</code></pre>
<p>读文件例1</p>
<pre><code><code>try:
    f = open(&#39;a.txt&#39;)
    g = (line.strip() for line in f)
    print(next(g))
    print(next(g))
    print(next(g))
    print(next(g))
    print(next(g))
except StopIteration:
    f.close()

&#39;&#39;&#39;
next(g)会触发迭代f，依次next(g)就可以读取文件的一行行内容，无论文件a.txt有多大，同一时刻内存中只有一行内容。
提示：g是基于文件句柄f而存在的，因而只能在next(g)抛出异常StopIteration后才可以执行f.close()
&#39;&#39;&#39;</code></pre>
<p>读文件例2</p>
<h4 id="part2异常类只能用来处理指定的异常情况.">**part2:异常类只能用来处理指定的异常情况.</h4>
<pre><code><code># 未捕获到异常，程序直接报错
 
s1 = &#39;hello&#39;
try:
    int(s1)
except IndexError as e:
    print e</code></pre>
<h4 id="part3多分支">**part3:多分支</h4>
<pre><code><code>s1 = &#39;hello&#39;
try:
    int(s1)
except IndexError as e:
    print(e)
except KeyError as e:
    print(e)
except ValueError as e:
    print(e)</code></pre>
<h4 id="part4万能异常exception."><strong>part4:万能异常:Exception.</strong></h4>
<p><strong>他可以捕获任意异常，即：</strong></p>
<pre><code><code>s1 = &#39;hello&#39;
try:
    int(s1)
except Exception as e:
    print(e)</code></pre>
<p>你可能会说既然有万能异常，那么我直接用上面的这种形式就好了，其他异常可以忽略</p>
<p>你说的没错，但是应该分两种情况去看</p>
<p>1.如果你想要的效果是，无论出现什么异常，我们统一丢弃，或者使用同一段代码逻辑去处理他们，那么骚年，大胆的去做吧，只有一个Exception就足够了。</p>
<pre><code><code>s1 = &#39;hello&#39;
try:
    int(s1)
except Exception,e:
    &#39;丢弃或者执行其他逻辑&#39;
    print(e)

#如果你统一用Exception，没错，是可以捕捉所有异常，但意味着你在处理所有异常时都使用同一个逻辑去处理（这里说的逻辑即当前expect下面跟的代码块）</code></pre>
<p>Exception</p>
<p>2.如果你想要的效果是，对于不同的异常我们需要定制不同的处理逻辑，那就需要用到多分支了。</p>
<pre><code><code>s1 = &#39;hello&#39;
try:
    int(s1)
except IndexError as e:
    print(e)
except KeyError as e:
    print(e)
except ValueError as e:
    print(e)</code></pre>
<p>多分支</p>
<pre><code><code>s1 = &#39;hello&#39;
try:
    int(s1)
except IndexError as e:
    print(e)
except KeyError as e:
    print(e)
except ValueError as e:
    print(e)
except Exception as e:
    print(e)
</code></pre>
<p>多分支+Exception</p>
<h4 id="part5异常的其他机构">**part5:异常的其他机构</h4>
<pre><code><code>s1 = &#39;hello&#39;
try:
    int(s1)
except IndexError as e:
    print(e)
except KeyError as e:
    print(e)
except ValueError as e:
    print(e)
#except Exception as e:
#    print(e)
else:
    print(&#39;try内代码块没有异常则执行我&#39;)
finally:
    print(&#39;无论异常与否,都会执行该模块,通常是进行清理工作&#39;)
</code></pre>
<h4 id="part6主动触发异常"><strong>part6:主动触发异常</strong></h4>
<pre><code><code>try:
    raise TypeError(&#39;类型错误&#39;)
except Exception as e:
    print(e)
</code></pre>
<h4 id="part7自定义异常">**part7:自定义异常</h4>
<pre><code><code>class EvaException(BaseException):
    def __init__(self,msg):
        self.msg=msg
    def __str__(self):
        return self.msg

try:
    raise EvaException(&#39;类型错误&#39;)
except EvaException as e:
    print(e)
</code></pre>
<h4 id="part8断言"><strong>part8:断言</strong></h4>
<pre><code><code># assert 条件
 
assert 1 == 1
 
assert 1 == 2
</code></pre>
<h4 id="part9try..except的方式比较if的方式的好处"><strong>part9：try..except的方式比较if的方式的好处</strong></h4>
<p>try..except这种异常处理机制就是取代if那种方式，让你的程序在不牺牲可读性的前提下增强健壮性和容错性</p>
<p>异常处理中为每一个异常定制了异常类型（python中统一了类与类型，类型即类），对于同一种异常，一个except就可以捕捉到，可以同时处理多段代码的异常（无需‘写多个if判断式’）减少了代码，增强了可读性</p>
<p>使用try..except的方式</p>
<p>1：把错误处理和真正的工作分开来<br />
2：代码更易组织，更清晰，复杂的工作任务更容易实现；<br />
3：毫无疑问，更安全了，不至于由于一些小的疏忽而使程序意外崩溃了；</p>
<h3 id="什么时候用异常处理">什么时候用异常处理</h3>
<p>有的同学会这么想，学完了异常处理后，好强大，我要为我的每一段程序都加上try...except，干毛线去思考它会不会有逻辑错误啊，这样就很好啊，多省脑细胞===》2B青年欢乐多</p>
<p>try...except应该尽量少用，因为它本身就是你附加给你的程序的一种异常处理的逻辑，与你的主要的工作是没有关系的<br />
这种东西加的多了，会导致你的代码可读性变差，只有在有些异常无法预知的情况下，才应该加上try...except，其他的逻辑错误应该尽量修正</p>

</div>
</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>